#!/bin/bash
#
# Convenience wrapper for vtctlclient to issue commands to vtctl server
set -e

script_root=`dirname "${BASH_SOURCE}"`
source $script_root/env.sh
source $script_root/env-tablet.sh

exec vtctlclient -server $vtctl_server:15999 "$@"
